In [2]:
import pandas as pd
from itertools import chain
data = pd.read_csv('archive/ner_dataset.csv', encoding= 'unicode_escape')
data.head()
from sklearn.model_selection import train_test_split
from keras_preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
import numpy as np
import tensorflow
from tensorflow.keras import Sequential, Model, Input
from tensorflow.keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from tensorflow.keras.utils import plot_model

In [3]:
pd.read_json('PANDA-dataset\dataset\PANDA-annotated-100k-shard0.jsonl', lines=True)

,original,rewrite,selected_word,perturbed_category,source_data_type
0,"Gregg and his family owned 80% of the company,...",Mrs. Gregg and her family owned 80% of the com...,his,Woman,wiki
1,"Gregg and his family owned 80% of the company,...",Gregg and them family owned 80% of the company...,his,Non-Binary,wiki
2,"Gregg and his family owned 80% of the company,...","Gregg and her family owned 80% of the company,...",his,Woman,wiki
3,"Gregg and his family owned 80% of the company,...",Gregg and them family owned 80% of the company...,his,Non-Binary,wiki
4,"Gregg and his family owned 80% of the company,...","Gregg and his family owned 80% of the company,...",European,Hispanic or Latino,wiki
...,...,...,...,...,...
19995,"This is a nervy , risky film , and Villeneuve ...","This is a nervy, risky film, and Villeneuve ha...",Bibi,Non-Binary,sst
19996,"Unfortunately , that 's precisely what Arthur ...","Unfortunately, that's precisely what Alice Don...",Arthur,Woman,sst
19997,"Unfortunately , that 's precisely what Arthur ...","Unfortunately, that's precisely what Luna Dong...",Arthur,Non-Binary,sst
19998,The best part about `` Gangs '' was Daniel Day...,"The best part about ""Gangs"" was Daniel Day-Lewis.",Day-Lewis,Man,sst
19999,The best part about `` Gangs '' was Daniel Day...,"The best part about ""Gangs"" was Danielle Day-L...",Day-Lewis,Woman,sst

In [4]:
def get_dict_map(data, token_or_tag):
    tok2idx = {}
    idx2tok = {}
    
    if token_or_tag == 'token':
        vocab = list(set(data['Word'].to_list()))
    else:
        vocab = list(set(data['Tag'].to_list()))
    
    idx2tok = {idx:tok for  idx, tok in enumerate(vocab)}
    tok2idx = {tok:idx for  idx, tok in enumerate(vocab)}
    return tok2idx, idx2tok

In [5]:
token2idx, idx2token = get_dict_map(data, 'token')
tag2idx, idx2tag = get_dict_map(data, 'tag')

In [6]:
token2idx

{'Cozumel': 0,
 'basing': 1,
 'reaffirmed': 2,
 'Horizons': 3,
 'Gotovina': 4,
 'blast': 5,
 'U2': 6,
 'compensated': 7,
 'knowledge-based': 8,
 'Hogg': 9,
 'Culture': 10,
 'Denmark-Sweden': 11,
 'forgo': 12,
 'Wikipedia': 13,
 '1,000-year': 14,
 'encouragement': 15,
 '68-year-old': 16,
 'unwanted': 17,
 'Hendarso': 18,
 'Garza': 19,
 'third-ranked': 20,
 'award': 21,
 '125': 22,
 'Flavia': 23,
 'Ipsos': 24,
 'Nalchik': 25,
 'Cambodian': 26,
 'Casablanca': 27,
 'kilometer-per-hour': 28,
 'paddy': 29,
 'bbl/day': 30,
 'uncalculated': 31,
 'medications': 32,
 'MONUC': 33,
 'Gwyneth': 34,
 'national-level': 35,
 'Shaktoi': 36,
 'detained': 37,
 'Donald': 38,
 'sanctuaries': 39,
 'react': 40,
 'ideological': 41,
 'newscaster': 42,
 'casual': 43,
 'worrisome': 44,
 'Aufdenblatten': 45,
 'Dai': 46,
 'Tombstone': 47,
 'ability': 48,
 'damaging': 49,
 'Qom': 50,
 'Stiff': 51,
 'Eduard': 52,
 'eight-tenths': 53,
 'Acting': 54,
 'laments': 55,
 'Spaniard': 56,
 'brokers': 57,
 'pro-Shiite': 58,
 'packing': 59,
 'Providencia': 60,
 'Tiananmen': 61,
 'anti-torture': 62,
 'indeed': 63,
 'Center': 64,
 'masterminded': 65,
 'Massum': 66,
 'partners': 67,
 'regency': 68,
 'cutbacks': 69,
 'bulk': 70,
 'Though': 71,
 'explores': 72,
 '1,675': 73,
 'Davos': 74,
 'poaching': 75,
 'Euphrates': 76,
 'Tunisians': 77,
 'Anibal': 78,
 'Ogero': 79,
 'Jerzy': 80,
 'Terms': 81,
 'precaution': 82,
 'vulnerabilities': 83,
 'Abia': 84,
 'Manila': 85,
 'declares': 86,
 'Afrikaners': 87,
 'Colosseum': 88,
 'mid-level': 89,
 'defend': 90,
 'Blades': 91,
 '32,000': 92,
 'skeptics': 93,
 'reprimands': 94,
 'defeat': 95,
 'THREE': 96,
 'Smyr': 97,
 '12-percent': 98,
 'Sindh': 99,
 'quoting': 100,
 'shantytown': 101,
 'License': 102,
 'rearming': 103,
 'proliferating': 104,
 'debts': 105,
 'soft': 106,
 'consensual': 107,
 'furniture': 108,
 'incorporated': 109,
 'Michigan': 110,
 'Assistance': 111,
 're-submit': 112,
 'Louisiana': 113,
 'continual': 114,
 'Sunday': 115,
 'sizably': 116,
 'Khetaguri': 117,
 'discharge': 118,
 'insight': 119,
 'writers': 120,
 'irremediable': 121,
 'barricade': 122,
 'el-Sheikh': 123,
 'Upali': 124,
 'pleading': 125,
 'spit': 126,
 '216': 127,
 'brewing': 128,
 'donate': 129,
 'murmured': 130,
 'Bent': 131,
 'You': 132,
 'Jufeng': 133,
 'Melilla': 134,
 'Nazarbayev': 135,
 'galleries': 136,
 'Bheri': 137,
 'Alcantara': 138,
 '1.16': 139,
 'generic': 140,
 'thin': 141,
 'earthenware': 142,
 'believed': 143,
 'Ground': 144,
 'approve': 145,
 'Karpinski': 146,
 'nationalize': 147,
 'rivals': 148,
 'KABILA': 149,
 'displays': 150,
 'restarting': 151,
 'randomly': 152,
 'ex-Soviet': 153,
 'Valle': 154,
 'refiner': 155,
 'Dye': 156,
 'Married': 157,
 'publicity': 158,
 'insect': 159,
 'Eelam': 160,
 'landholdings': 161,
 'Benito': 162,
 'discriminate': 163,
 'watchdog': 164,
 'Pride': 165,
 'authentic': 166,
 'subspecies': 167,
 'Al-Ahbash': 168,
 'emerged': 169,
 'milestone': 170,
 '86': 171,
 'REDD+': 172,
 '25-meter': 173,
 'tremor': 174,
 'machine-gun': 175,
 'web-slinging': 176,
 'Lamm': 177,
 'account-holders': 178,
 'Arc': 179,
 'Nad-e-Ali': 180,
 'Mashaie': 181,
 'Rong': 182,
 'hardships': 183,
 'liberties': 184,
 'Dir': 185,
 'condolence': 186,
 'identifying': 187,
 'KANU': 188,
 '1822': 189,
 'buildings': 190,
 '31': 191,
 'sold-out': 192,
 'Macedonia': 193,
 'Xerox': 194,
 'Militia': 195,
 'Ceylon': 196,
 'Megumi': 197,
 'reinstatement': 198,
 'financier': 199,
 'self-employment': 200,
 'outbreak': 201,
 'Adhaim': 202,
 'using': 203,
 'spill': 204,
 'ex-president': 205,
 '35,000': 206,
 'fee': 207,
 'Victims': 208,
 'fury': 209,
 'embankments': 210,
 'enriched': 211,
 'repairing': 212,
 'Aristide': 213,
 'brand': 214,
 'relaxing': 215,
 'seven': 216,
 'technologies': 217,
 'enter': 218,
 'budgetary': 219,
 'sea-based': 220,
 'bunker-busters': 221,
 'northeast': 222,
 'EFTA': 223,
 'intervening': 224,
 'Dinara': 225,
 'Paradorn': 226,
 'Moreover': 227,
 'caste': 228,
 'Anti-India': 229,
 'Azahari': 230,
 'basic': 231,
 'leased': 232,
 'Cocoa': 233,
 'anti-Castro': 234,
 'dead': 235,
 'urging': 236,
 'pieces': 237,
 'Choi': 238,
 'multi-year': 239,
 'Celia': 240,
 'Users': 241,
 'ceased': 242,
 'Associated': 243,
 'trees': 244,
 'Espiritu': 245,
 'domineering': 246,
 'profiteers': 247,
 '31,500': 248,
 'overvalued': 249,
 'semifinal': 250,
 'honorary': 251,
 'eighth-seeded': 252,
 'shoot': 253,
 'utmost': 254,
 'Jong-Chul': 255,
 'Cavalese': 256,
 'beatboxing': 257,
 'disruption': 258,
 'mid-April': 259,
 'al-Hamash': 260,
 'readies': 261,
 'terror': 262,
 'Diapers': 263,
 'Ireju': 264,
 'Exporting': 265,
 'First': 266,
 'explaining': 267,
 'workable': 268,
 'Pilgrim': 269,
 'Bobby': 270,
 'Currently': 271,
 'Yudhyono': 272,
 'Mohtarem': 273,
 'tells': 274,
 'Free-lance': 275,
 '17-year': 276,
 'resorted': 277,
 'Giro': 278,
 'spirit': 279,
 '2001': 280,
 'Zabol': 281,
 'Hound': 282,
 'Rauchenstein': 283,
 '11-judge': 284,
 'Notices': 285,
 'levee': 286,
 '03-Feb': 287,
 'thinning': 288,
 'MORALES': 289,
 'candlelit': 290,
 'Google': 291,
 'sheep-and-cattle': 292,
 'Navarro-Valls': 293,
 'violation': 294,
 'Ilham': 295,
 'il-Sung': 296,
 'insiders': 297,
 'Occidental': 298,
 'toughened': 299,
 'parliamentarian': 300,
 'Standard': 301,
 '25th': 302,
 'espionage': 303,
 'bankroll': 304,
 'betterment': 305,
 'Sumaidaie': 306,
 'also': 307,
 'disguise': 308,
 'vapor': 309,
 '235': 310,
 '500-million': 311,
 'Renaissance': 312,
 'bet': 313,
 'stormy': 314,
 'Catherine': 315,
 'Esfandiari': 316,
 'Najibullah': 317,
 'Saipan': 318,
 'imply': 319,
 'social-conservative': 320,
 'Kaplan': 321,
 'Bastion': 322,
 'Kidwa': 323,
 'Laurent': 324,
 'prohibitions': 325,
 'anywhere': 326,
 'misery': 327,
 'evictions': 328,
 'Pork': 329,
 'champ': 330,
 'argument': 331,
 'chief-of-staff': 332,
 'Klain': 333,
 'CAFTA': 334,
 'meteorological': 335,
 'Michelle': 336,
 'Powell': 337,
 'subsurface': 338,
 'vacuum': 339,
 'suppliers': 340,
 'warmongering': 341,
 'insects': 342,
 'Reebok': 343,
 'leveraged': 344,
 'Guadalupe': 345,
 'zidovudine': 346,
 'Iranian-made': 347,
 'Kgalema': 348,
 'crash': 349,
 'Davenport': 350,
 'When': 351,
 'chronicles': 352,
 'Montas': 353,
 '69-43': 354,
 'eleven': 355,
 'Chileans': 356,
 'purposes': 357,
 'sounds': 358,
 'wood': 359,
 'well': 360,
 'Machinea': 361,
 'booed': 362,
 'lies': 363,
 'Vejjajiva': 364,
 'Renewed': 365,
 'present-day': 366,
 'Zaire': 367,
 'causing': 368,
 'collects': 369,
 'medic': 370,
 'shelter': 371,
 'Jong-Nam': 372,
 'Santo': 373,
 'Eker': 374,
 'Asia-Pacific': 375,
 'all-around': 376,
 'Sarfraz': 377,
 'manipulate': 378,
 'Gazan': 379,
 'Mombasa-based': 380,
 'some': 381,
 'impunity': 382,
 'folly': 383,
 "O'Keeffe": 384,
 'fuels': 385,
 'blistering': 386,
 'unilaterally': 387,
 'U.S.': 388,
 'Pro-business': 389,
 'cowardly': 390,
 'immune': 391,
 'Small': 392,
 'deficiencies': 393,
 'Cotter': 394,
 'Color': 395,
 'capitalize': 396,
 '1,247': 397,
 '72': 398,
 'canning': 399,
 'Manipur': 400,
 'Ataturk': 401,
 'extravagant': 402,
 'skaters': 403,
 'tiny': 404,
 'encompass': 405,
 'Repubblica': 406,
 'mere': 407,
 'Rajoelina': 408,
 'Rod': 409,
 'focuses': 410,
 'co-hosted': 411,
 'flowing': 412,
 'Val-de-Grace': 413,
 'Babaker': 414,
 '19-nation': 415,
 'Domachowska': 416,
 'rejoined': 417,
 'bootleg': 418,
 'Nativity': 419,
 'Damascus': 420,
 'restricts': 421,
 'opposition-aligned': 422,
 'low-level': 423,
 'busiest': 424,
 'Arjangi': 425,
 'Quan': 426,
 'Reinhardt': 427,
 'Ouwa': 428,
 'ladders': 429,
 '4,38,000': 430,
 'ballot': 431,
 'capacity': 432,
 'intimidating': 433,
 'amounted': 434,
 'venomous': 435,
 'RICH': 436,
 'Hofstad': 437,
 'Sagues': 438,
 'restored': 439,
 'Tain': 440,
 'racquetball': 441,
 'surged': 442,
 'Adams': 443,
 'lackluster': 444,
 'lowest': 445,
 'Patch': 446,
 'Trans-Saharan': 447,
 'Ronald': 448,
 'Vigorous': 449,
 'coaches': 450,
 'low-grade': 451,
 'Stanilas': 452,
 'Sapporo': 453,
 'annual': 454,
 'rape': 455,
 'yet-to-be-announced': 456,
 'jurists': 457,
 'al-Ghazal': 458,
 'Sociology': 459,
 'Takirambudde': 460,
 'Pajhwok': 461,
 'Reconnaissance': 462,
 'mask-wearing': 463,
 'eggs': 464,
 'AIDS-prevention': 465,
 'Torrential': 466,
 'Evi': 467,
 'meanwhile': 468,
 're-establish': 469,
 'Ronaldinho': 470,
 'low-pressure': 471,
 'sale': 472,
 'justices': 473,
 'Minnesota': 474,
 'prison': 475,
 'Aside': 476,
 'reparations': 477,
 'Yongbyong': 478,
 'Exports': 479,
 'carrying': 480,
 'domination': 481,
 'percent': 482,
 'guise': 483,
 'Samo': 484,
 'disguised': 485,
 'parallel': 486,
 "o'er": 487,
 'drink': 488,
 'veered': 489,
 'al-Suraiwi': 490,
 'CAT': 491,
 'absorbs': 492,
 'spouse': 493,
 'globalization': 494,
 'concerning': 495,
 'icon': 496,
 'Tshisekedi': 497,
 'Cairo': 498,
 'Malawai': 499,
 'U-2s': 500,
 'victims': 501,
 'Urtuzaga': 502,
 'graduate': 503,
 'Battalion': 504,
 'two-dozen': 505,
 'Day': 506,
 'Korean-flagged': 507,
 'Dasain': 508,
 'collectivization': 509,
 'Kapil': 510,
 'mainly': 511,
 'conflicts': 512,
 'Maier': 513,
 'ingesting': 514,
 'goo': 515,
 'RUTTE': 516,
 'Kilinochchi': 517,
 'wet': 518,
 'provincal': 519,
 'Cykla': 520,
 'hope': 521,
 'artemisinin': 522,
 'Everado': 523,
 'Gradual': 524,
 'persuading': 525,
 'informed': 526,
 'credibility': 527,
 'Delhi-based': 528,
 'uncensored': 529,
 'convenience': 530,
 'behalf': 531,
 'Dheere': 532,
 'tactic': 533,
 'Dawei-Ye': 534,
 'Jewish-owned': 535,
 'eventually': 536,
 'outperformed': 537,
 'Low': 538,
 'militancy': 539,
 'Russell': 540,
 'grief': 541,
 'Duncan': 542,
 'Dome': 543,
 'gunshot': 544,
 'Siniora': 545,
 "Shi'ites": 546,
 'to': 547,
 'thought': 548,
 'donating': 549,
 'scared': 550,
 'mid-February': 551,
 'Kahar': 552,
 'psychology': 553,
 '7.4': 554,
 'Glyn': 555,
 'dry': 556,
 'crossings': 557,
 'blower': 558,
 'annualized': 559,
 'they': 560,
 'convey': 561,
 'misleading': 562,
 'headdress': 563,
 'all-cash': 564,
 'Rangel': 565,
 'Hasina': 566,
 'dietary': 567,
 'Iranian': 568,
 'Chimango': 569,
 'Rugova': 570,
 'outage': 571,
 'E.': 572,
 'Vahidi': 573,
 'Jadoon': 574,
 'components': 575,
 'mid-2007': 576,
 'professors': 577,
 'Hallmark': 578,
 'sustaining': 579,
 'lots': 580,
 'coins': 581,
 'Ljubotno': 582,
 '14th-century': 583,
 'coerced': 584,
 '1.5': 585,
 'apparently': 586,
 're-examine': 587,
 '05-Jul': 588,
 'guided': 589,
 'implored': 590,
 'sunspots': 591,
 'Sharapova': 592,
 'orchids': 593,
 'Poleo': 594,
 'Reform': 595,
 'failed': 596,
 'coaltion': 597,
 'Mowaffaq': 598,
 'tore': 599,
 'Osaka': 600,
 'drug-fueled': 601,
 'engine': 602,
 'Adrien': 603,
 'Mu': 604,
 'Soaring': 605,
 'Connick': 606,
 '10-Dec': 607,
 'Eve': 608,
 'Romano': 609,
 'kept': 610,
 'Al': 611,
 'Fatou': 612,
 'CRJ-200s': 613,
 'Sufa': 614,
 'Crvenkovski': 615,
 'Mirnyi': 616,
 'venues': 617,
 'Austin': 618,
 'Jomo': 619,
 'braces': 620,
 'latitude': 621,
 'party': 622,
 'Giustra': 623,
 'Operation': 624,
 'Raufi': 625,
 'Scotland': 626,
 'legislatures': 627,
 '729.88': 628,
 'limb': 629,
 'formal': 630,
 'seat': 631,
 'Vladimir': 632,
 'Being': 633,
 'sake': 634,
 'injection': 635,
 'occasionally': 636,
 'Two-time': 637,
 'Canal': 638,
 'Orinoco': 639,
 'Anti-Chinese': 640,
 'violates': 641,
 'compliment': 642,
 'offenses': 643,
 'Farhat': 644,
 'astronauts': 645,
 'Smaller': 646,
 'Accordance': 647,
 'Mashona': 648,
 'homing': 649,
 'Barba': 650,
 'militaries': 651,
 'Uhm': 652,
 'year-on-year': 653,
 'digits': 654,
 'cancers': 655,
 'IDPs': 656,
 'Immediately': 657,
 'moviegoers': 658,
 'stung': 659,
 'bacteria': 660,
 'Shawal': 661,
 'copy': 662,
 'reaping': 663,
 'premature': 664,
 '65th': 665,
 'Courtney': 666,
 'Serhiy': 667,
 'Harun': 668,
 'villas': 669,
 'Fig-Tree': 670,
 'Carlos': 671,
 'resonated': 672,
 'Realtors': 673,
 'al-Falluji': 674,
 'More': 675,
 'dictators': 676,
 'sped': 677,
 'revert': 678,
 'spacewalk': 679,
 'shock': 680,
 'orbited': 681,
 'notoriously': 682,
 'cyclone': 683,
 'Adolfo': 684,
 'raffle': 685,
 'Million': 686,
 'objectivity': 687,
 'Radak': 688,
 'firehouses': 689,
 'Nevsky': 690,
 'ward': 691,
 'Dane': 692,
 'SUMMER': 693,
 'Tachilek': 694,
 'Yahya': 695,
 '263': 696,
 'exist': 697,
 'shuttle': 698,
 'chlorine': 699,
 'brawny': 700,
 '2,70,000': 701,
 'incessant': 702,
 'Nhlanhla': 703,
 'someday': 704,
 'Gronholm': 705,
 'pouring': 706,
 'Shepherds': 707,
 'rated': 708,
 'Society': 709,
 'layoffs': 710,
 'achieving': 711,
 'betraying': 712,
 'life-saving': 713,
 'inter-linked': 714,
 'remainder': 715,
 'Soccer': 716,
 'veterinarian': 717,
 'emphasis': 718,
 'condoms': 719,
 'speeds': 720,
 'rightists': 721,
 'plague': 722,
 'Jane': 723,
 '5,19,000': 724,
 'realizes': 725,
 'tables': 726,
 'bystanders': 727,
 'pro-al-Qaida': 728,
 'effigies': 729,
 'Perisic': 730,
 'Pablo': 731,
 'SEAGULL': 732,
 'six-thousand': 733,
 'factional': 734,
 'Raymond': 735,
 'Lausanne-based': 736,
 'Glacier': 737,
 'Feb-88': 738,
 'counter-terrorism': 739,
 'platform': 740,
 'surety': 741,
 'rejected': 742,
 'crossroads': 743,
 'Kosachyov': 744,
 'leases': 745,
 'el-Shater': 746,
 'Espersen': 747,
 'Successful': 748,
 'Embraer': 749,
 'Rocio': 750,
 'counselor': 751,
 'stalking': 752,
 'Partridge': 753,
 'Ministries': 754,
 'Busan': 755,
 'Amrullah': 756,
 'Police': 757,
 'Michel': 758,
 'Bong-jo': 759,
 'bearing': 760,
 'bilingual': 761,
 'Rockefeller': 762,
 'KIBAKI': 763,
 'Memphis': 764,
 'Pedraz': 765,
 'Paulo': 766,
 'Afghan-international': 767,
 'diver': 768,
 'sanitary': 769,
 'low-ranking': 770,
 'Isfahan': 771,
 'Yahoo': 772,
 'APS': 773,
 'that': 774,
 'pluck': 775,
 'Baqubah': 776,
 'metal': 777,
 'safeguards': 778,
 '111th': 779,
 'bulldozing': 780,
 'Wade': 781,
 'battleship': 782,
 'Athletics': 783,
 'Cambodians': 784,
 'blaze': 785,
 'impression': 786,
 'begins': 787,
 'Keifer': 788,
 'Mil': 789,
 'Qaumi': 790,
 'inroads': 791,
 'move': 792,
 'Blackhawk': 793,
 'hazards': 794,
 'stronger': 795,
 'Bibles': 796,
 'worth': 797,
 'importation': 798,
 'victory': 799,
 'Albania': 800,
 'Baker': 801,
 '2.2': 802,
 'indexes': 803,
 'balletic': 804,
 'compensate': 805,
 'bawdy': 806,
 'Congressional-Executive': 807,
 'portrait': 808,
 'economist': 809,
 'peeling': 810,
 'vampire': 811,
 'deserter': 812,
 'jumpstart': 813,
 'Nansan': 814,
 'Gambari': 815,
 'videolink': 816,
 'Jesper': 817,
 'Kris': 818,
 'Peipah': 819,
 'chairs': 820,
 'Commodore': 821,
 'lamppost': 822,
 'haste': 823,
 'Yucatan': 824,
 'fault': 825,
 'security': 826,
 'U.S.-funded': 827,
 'electrical': 828,
 'Opportunity': 829,
 'Anez': 830,
 'alimony': 831,
 'compound': 832,
 'acknowledging': 833,
 'Razak': 834,
 "Ba'ath": 835,
 'sworn': 836,
 'Condoleeza': 837,
 'Out': 838,
 'implanted': 839,
 '24,000': 840,
 'reference': 841,
 'implemented': 842,
 'governor': 843,
 'firm': 844,
 'El-Obeid': 845,
 'bamboo': 846,
 'sequence': 847,
 'Disputes': 848,
 'farther': 849,
 'guaranteeing': 850,
 'perpetrating': 851,
 'services-based': 852,
 'retailer': 853,
 'congratulated': 854,
 'al-Qawasmi': 855,
 'donkey': 856,
 'rallied': 857,
 'Karua': 858,
 'blasts': 859,
 'dinosaurs': 860,
 'harvest': 861,
 'Maurits': 862,
 'helps': 863,
 'sealing': 864,
 'Western': 865,
 'Zigazag': 866,
 'Segolene': 867,
 'ambushing': 868,
 '1932': 869,
 'trod': 870,
 'mutating': 871,
 'de-facto': 872,
 'voluntarily': 873,
 'EUFOR': 874,
 '0.08': 875,
 'dampened': 876,
 'learned': 877,
 'Obamas': 878,
 'Jessye': 879,
 'Mladic': 880,
 'unilateral': 881,
 'parking': 882,
 'Hafun': 883,
 '15-Feb': 884,
 'Badoosh': 885,
 'Petraeus': 886,
 'lighthearted': 887,
 'yields': 888,
 'pro-independence': 889,
 'legitimate': 890,
 'installs': 891,
 'Rodier': 892,
 'Qeshm': 893,
 'elaborating': 894,
 'democratically': 895,
 'leaner': 896,
 "d'Urgell": 897,
 'synchronize': 898,
 'primacy': 899,
 'Shimon': 900,
 'For': 901,
 'Caicos': 902,
 'hectares': 903,
 'Barretto': 904,
 'wear': 905,
 'Tarawa': 906,
 'Hanouichi': 907,
 'Heritage': 908,
 'Mich.-based': 909,
 'galaxies': 910,
 '[': 911,
 'Yonts': 912,
 'militant-appointed': 913,
 'Nauru': 914,
 'stroll': 915,
 'inappropriate': 916,
 'traditionally': 917,
 'unmanned': 918,
 'partisan': 919,
 'Sub-Saharan': 920,
 'drawing': 921,
 '43rd-ranked': 922,
 'Delegate': 923,
 'exploitable': 924,
 'Evgeny': 925,
 'Gijs': 926,
 'Yekiti': 927,
 'warehouses': 928,
 'Kyrgyzstan': 929,
 'plea': 930,
 'realestate': 931,
 'Climate': 932,
 'Reese': 933,
 'nutrition': 934,
 'Momir': 935,
 'posses': 936,
 'wheel': 937,
 'escalating': 938,
 'outcome': 939,
 'rhythm-and-blues': 940,
 'meekness': 941,
 'cooperative': 942,
 'stake': 943,
 '38.7': 944,
 'Echo': 945,
 'disturbed': 946,
 'acclaim': 947,
 'Departments': 948,
 'Moor': 949,
 'implications': 950,
 'meeting': 951,
 'culmination': 952,
 'attach': 953,
 'inhabit': 954,
 'misunderstandings': 955,
 'Unified': 956,
 'Maud': 957,
 'Maathai': 958,
 'G-CAPP': 959,
 'ignite': 960,
 'glory': 961,
 'Liaoning': 962,
 'urges': 963,
 'torching': 964,
 'unrest': 965,
 'Feyzabad': 966,
 'short-wave': 967,
 'five-nation': 968,
 'Kaohsiung': 969,
 '666': 970,
 'al-Qaida-linked': 971,
 'internationally-recognized': 972,
 'detonated': 973,
 'Deif': 974,
 'Noble': 975,
 'Haas': 976,
 'Cannon': 977,
 'file': 978,
 '273': 979,
 'Amerindian': 980,
 'Zhang': 981,
 'Union-sponsored': 982,
 'Lauder': 983,
 'supermarket': 984,
 'consitutional': 985,
 'interviewed': 986,
 'Donetsk': 987,
 'Campo': 988,
 'Abercrombie': 989,
 'Sarah': 990,
 'breed': 991,
 'Syarhei': 992,
 'Same-sex': 993,
 'Gruevski': 994,
 '5.7-kilometer': 995,
 'agonies': 996,
 'disobey': 997,
 'Khomeini': 998,
 'suggests': 999,
 ...}

In [7]:
data['Word_idx'] = data['Word'].map(token2idx)
data['Tag_idx'] = data['Tag'].map(tag2idx)
data.head()

    Sentence #           Word  POS Tag  Word_idx  Tag_idx
0  Sentence: 1      Thousands  NNS   O      9815        7
1          NaN             of   IN   O      3446        7
2          NaN  demonstrators  NNS   O     15977        7
3          NaN           have  VBP   O      2142        7
4          NaN        marched  VBN   O     17605        7

In [8]:
# Fill na
data_fillna = data.ffill(axis=0)# Groupby and collect columns
data_group = data_fillna.groupby(
['Sentence #'],as_index=False
).agg(lambda x: list(x))# Visualise data
data_group.head()

,Sentence #,Word,POS,Tag,Word_idx,Tag_idx
0,Sentence: 1,"[Thousands, of, demonstrators, have, marched, ...","[NNS, IN, NNS, VBP, VBN, IN, NNP, TO, VB, DT, ...","[O, O, O, O, O, O, B-geo, O, O, O, O, O, B-geo...","[9815, 3446, 15977, 2142, 17605, 25172, 8397, ...","[7, 7, 7, 7, 7, 7, 13, 7, 7, 7, 7, 7, 13, 7, 7..."
1,Sentence: 10,"[Iranian, officials, say, they, expect, to, ge...","[JJ, NNS, VBP, PRP, VBP, TO, VB, NN, TO, JJ, J...","[B-gpe, O, O, O, O, O, O, O, O, O, O, O, O, O,...","[568, 30583, 31575, 560, 24831, 547, 13975, 34...","[9, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, ..."
2,Sentence: 100,"[Helicopter, gunships, Saturday, pounded, mili...","[NN, NNS, NNP, VBD, JJ, NNS, IN, DT, NNP, JJ, ...","[O, O, B-tim, O, O, O, O, O, B-geo, O, O, O, O...","[2293, 32816, 26813, 3336, 13195, 5091, 20016,...","[7, 7, 3, 7, 7, 7, 7, 7, 13, 7, 7, 7, 7, 7, 1,..."
3,Sentence: 1000,"[They, left, after, a, tense, hour-long, stand...","[PRP, VBD, IN, DT, NN, JJ, NN, IN, NN, NNS, .]","[O, O, O, O, O, O, O, O, O, O, O]","[31231, 12531, 2934, 13633, 32837, 33693, 2000...","[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]"
4,Sentence: 10000,"[U.N., relief, coordinator, Jan, Egeland, said...","[NNP, NN, NN, NNP, NNP, VBD, NNP, ,, NNP, ,, J...","[B-geo, O, O, B-per, I-per, O, B-tim, O, B-geo...","[24201, 15951, 18746, 29290, 18231, 28777, 115...","[13, 7, 7, 12, 16, 7, 3, 7, 13, 7, 9, 7, 9, 7,..."

In [9]:
def get_pad_train_test_val(data_group, data):

    #get max token and tag length
    n_token = len(list(set(data['Word'].to_list())))
    n_tag = len(list(set(data['Tag'].to_list())))

    #Pad tokens (X var)    
    tokens = data_group['Word_idx'].tolist()
    maxlen = max([len(s) for s in tokens])
    pad_tokens = pad_sequences(tokens, maxlen=maxlen, dtype='int32', padding='post', value= n_token - 1)

    #Pad Tags (y var) and convert it into one hot encoding
    tags = data_group['Tag_idx'].tolist()
    pad_tags = pad_sequences(tags, maxlen=maxlen, dtype='int32', padding='post', value= tag2idx["O"])
    n_tags = len(tag2idx)
    pad_tags = [to_categorical(i, num_classes=n_tags) for i in pad_tags]
    
    #Split train, test and validation set
    tokens_, test_tokens, tags_, test_tags = train_test_split(pad_tokens, pad_tags, test_size=0.1, train_size=0.9, random_state=2020)
    train_tokens, val_tokens, train_tags, val_tags = train_test_split(tokens_,tags_,test_size = 0.25,train_size =0.75, random_state=2020)

    print(
        'train_tokens length:', len(train_tokens),
        '\ntrain_tokens length:', len(train_tokens),
        '\ntest_tokens length:', len(test_tokens),
        '\ntest_tags:', len(test_tags),
        '\nval_tokens:', len(val_tokens),
        '\nval_tags:', len(val_tags),
    )
    
    return train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags

train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = get_pad_train_test_val(data_group, data)

train_tokens length: 32372
train_tokens length: 32372
test_tokens length: 4796
test_tags: 4796
val_tokens: 10791
val_tags: 10791

In [10]:
from numpy.random import seed
seed(1)
tensorflow.random.set_seed(2)

In [12]:
input_dim = len(list(set(data['Word'].to_list())))+1
output_dim = 64
input_length = max([len(s) for s in data_group['Word_idx'].tolist()])
n_tags = len(tag2idx)
print('input_dim: ', input_dim, '\noutput_dim: ', output_dim, '\ninput_length: ', input_length, '\nn_tags: ', n_tags)

input_dim:  35179
output_dim:  64
input_length:  104
n_tags:  17

In [13]:
def get_bilstm_lstm_model():
    model = Sequential()

    # Add Embedding layer
    model.add(Embedding(input_dim=input_dim, output_dim=output_dim, input_length=input_length))

    # Add bidirectional LSTM
    model.add(Bidirectional(LSTM(units=output_dim, return_sequences=True, dropout=0.2, recurrent_dropout=0.2), merge_mode = 'concat'))

    # Add LSTM
    model.add(LSTM(units=output_dim, return_sequences=True, dropout=0.5, recurrent_dropout=0.5))

    # Add timeDistributed Layer
    model.add(TimeDistributed(Dense(n_tags, activation="relu")))

    #Optimiser 
    optimizer = tensorflow.keras.optimizers.Adam(lr=0.01, decay=1e-6)

    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    model.summary()
    
    return model

In [14]:
def train_model(X, y, model):
    loss = list()
    for i in range(25):
        # fit model for one epoch on this sequence
        hist = model.fit(X, y, batch_size=1000, verbose=1, epochs=1, validation_split=0.2)
        loss.append(hist.history['loss'][0])
    return loss

In [15]:
results = pd.DataFrame()
model_bilstm_lstm = get_bilstm_lstm_model()
plot_model(model_bilstm_lstm)
results['with_add_lstm'] = train_model(train_tokens, np.array(train_tags), model_bilstm_lstm)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 104, 64)           2251456

 bidirectional (Bidirectiona  (None, 104, 128)         66048
 l)

 lstm_1 (LSTM)               (None, 104, 64)           49408

 time_distributed (TimeDistr  (None, 104, 17)          1105
 ibuted)

=================================================================
Total params: 2,368,017
Trainable params: 2,368,017
Non-trainable params: 0
_________________________________________________________________
You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.
21/26 [=======================>......] - ETA: 40s - loss: 1.2289 - accuracy: 0.9160